#!/usr/bin/env bash
. $HOME/.config/theme-manager-bspwm/scripts/utils

update() {
    if [[ " ${themes[@]} " =~ " ${MENU} " ]]; then 
        change_n_source PTHEME $MENU
        change_poly $MENU
    fi
}
display_rofi() {
    MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p '' \
    -theme $BT \
    <<< "$(echo $list)")"
}

display_rofi
update
