#!/usr/bin/env bash
wm_theme="$HOME/.config/theme-manager-bspwm/conf"
. $wm_theme

SDIR="$HOME/.config/polybar/$PTHEME/scripts"
dir="$HOME/.config/polybar"
RDIR="$HOME/.config/rofi/launchers/colorful/$RTHEME.rasi"

BT="$HOME/.config/rofi/launchers/text/$BMENU"
themes=(`ls --hide="launch.sh" --hide="panels" --hide="pwidgets" --hide="basic_config.ini" --hide="scripts" $dir`)
list=$( IFS=$'|'; echo "${themes[*]}" )

srct() {
    . $wm_theme
}

change_poly() {
    echo "[✗] Changing polybar..."
    bspc config top_padding 0
    bspc config bottom_padding 0
    wal -c
    bash $dir/scripts/pywal.sh $PTHEME $HOME/.wall
    bash $dir/$PTHEME/launch.sh
    
}
sub_val() {
    sed -i "s/\($1=\"\)[aA-zZ0-9]*/\1$2/" $wm_theme
    srct
}
change_n_source() {
    sub_val $1 $2
    srct 
}
gen_wall() {
    echo "[✗] Changing wallpaper..."
    cp $1 $HOME/.wall
}
fill() {
    feh --bg-fill $HOME/.wall
}

config_launcher() {
    echo "[✗] Changing theme of launcher..."
    sed  -i "s|\(\$HOME/.*/.*/.*/.*/\).*\(\.rasi\)|\1$RTHEME\2|" $HOME/.config/sxhkd/sxhkdrc
    pkill -USR1 -x sxhkd
}
#config_net_dmenu() {
    #echo "[✗] Changing theme of network manager dmenu..."
    #sed -i "s_\(~/\.config/polybar/\)[aA-zZ]*\(/scripts/rofi/networkmenu\.rasi\)_\1$PTHEME\2_" $HOME/.config/networkmanager-dmenu/config.ini
#}



