#!/usr/bin/env bash
base_dir=$HOME/.config
polybar_dir=$base_dir/polybar
kitty_dir=$base_dir/kitty
neofetch_dir=$base_dir/neofetch
rofi_dir=$base_dir/rofi
vimrc=$HOME/.vimrc
bin_dir=$HOME/.bin
wallpapers_dir=$HOME/.wallpapers
picom_dir=$base_dir/picom
bspwm_dir=$base_dir/bspwm
sxhkd_dir=$base_dir/sxhkd

echo "Do not worry.
No any files or directory of yours will be overwritten. 😊
    "

install_tp() {
    title=$1
    fdir=$2
    mdir=$3
    echo -n "Want $1? [y] / [n] "
    read choice
    if [[ ${choice,,} = "y" ]]; then
        if [[ -d $2 ]] || [[ -f $2 ]];then
            echo -n "[✗] $1 exist. [b]ackup / [c]ancel?"
            read choice 

            if [[ ${choice,,} = "b" ]]; then
                rand=$(date +%S%N%w%H%y%M)
                echo "[✗] Backuping $title" "$fdir ==> $fdir.$rand"
                mv $fdir $fdir.$rand
                echo "[✗] Adding $mdir ==> $fdir"
                cp -r $mdir $fdir
                echo "[✌️]  $1 is added."
            else
                echo "[✗] Skipping $1."
            fi

        else
            echo "[✗] Adding $mdir ==> $fdir"
            cp -r $mdir $fdir
            echo "[✌️]  $1 is added."
        fi
    else
        echo "[✗] Skipping $1."
    fi

}

install_tp polybar $polybar_dir .config/polybar
install_tp rofi $rofi_dir .config/rofi 
install_tp kitty $kitty_dir .config/kitty
install_tp neofetch $neofetch_dir .config/neofetch
install_tp .vimrc $vimrc .vimrc
install_tp .wallpapers $wallpapers_dir .wallpapers
install_tp .bin $bin_dir .bin
install_tp picom $picom_dir .config/picom
install_tp bspwm $bspwm_dir .config/bspwm
install_tp sxhkd $sxhkd_dir .config/sxhkd
echo "[✌️]  Phase 1 done!!"
bash .config/theme-build/install
echo "[✌️]  Done!!"
