#!/usr/bin/env bash
trap '' INT
VERSION=1.2

ver() {
    echo [🚀] $VERSION
    exit 0
}
bad() {
    echo [🔥] Bad Command. 
    help
}

help() {
    cat << EOF
Usage: ctc <file-name>

REQUIRED: (xclip)
With no file, read standard input. 

    -h --help       Display this help and exit
    -v --verision   Display the version of the script
EOF
exit 0
}
copy() {
    echo "$1" | xclip -selection clipboard
    echo -e "[✨] Copied to clipboard..."
}
from_stdin() {
    trap 'echo' INT
    in=$(cat)
    copy "$in"

}
from_file() {
    cat $1 | xclip -selection clipboard
    echo "[✨] Copied to clipboard from $1"
}

case $1 in
    -h|--help)
        help
        ;;
    -v|--version)
        ver
        ;;
    -*|--*)
        bad
        ;;
esac


if [[ ! -f "/usr/bin/xclip" ]];
then 
    echo "[🚨] xclip required.."
    exit 0
fi

if [[ ! -f "$1" ]] 
then
    if [[ $1 == "" ]]; then 
    from_stdin
else 
    echo "[🚨] No such file found."
    fi
else
    from_file $1
fi
