#!/usr/bin/env bash

# ----------------------------------------------------------+
# Author:               sujan parajuli                      |
# Description:          Copy content of file to clipboard   | 
# Require:              xclip program                       |
# ----------------------------------------------------------+
if test -z "$1"
then
    echo "Please specify some file"
else
    cat $1 | xclip -selection clipboard
    echo "copied to clipboard from $1"
fi
