#!/usr/bin/bash

#Fast File Explorer
#Kinda. With the help of dmenu, ofcourse

FONT="Source Code Variable"
TERMINAL=kitty

EDITOR=nvim
VIMRC=$HOME/.vimrc
ZSHRC=$HOME/.config/zsh/.zshrc
PICOM=$HOME/.config/picom/picom.conf
SXHKDRC=$HOME/.config/sxhkd/sxhkdrc
BSPWMRC=$HOME/.config/bspwm/bspwmrc
LFRC=$HOME/.config/lf/lfrc
POLYBAR=$HOME/.config/polybar/config
SELF=$HOME/.bin/dmenu_common
XINITRC=$HOME/.xinitrc
XRESOURCES=$HOME/.Xresources
KITTY=$HOME/.config/kitty/kitty.conf



#Note: Colors are extracted from .Xresources.
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors
BG=$BACKGROUND
FG=$FOREGROUND
SELECTED_BG=$CYAN
SELECTED_FG=$BLACK

not_valid_msg() {
    notify-send "Not a valid command." "$1"
}


exec_cmd() {
    cmd="$1"
    $TERMINAL sh -c "$cmd; read"
}

edit() {
    dest=$1
    $TERMINAL -1 -e $EDITOR $dest
}
PROMPT="🚀"
BEGIN=""
END=""

options=(
"self"
"vimrc"
"zshrc"
"picom"
"bspwmrc"
"sxhkdrc"
"update"
"lfrc"
"polybar"
"xinitrc"
"xresources"
"kitty"
)


choice=$(printf "%s\n"  "${options[@]}" | dmenu -p "$PROMPT" -fn "$FONT" -nb $BG \
    -nf $FG -sb $SELECTED_BG -sf $SELECTED_FG)

case $choice in 
    "")
        exit
        ;;
    "self")
        edit $SELF
        ;;
    "vimrc")
        edit $VIMRC
        ;;
    "zshrc")
        edit $ZSHRC
        ;;
    "picom")
        edit $PICOM
        ;;
    "bspwmrc")
        edit $BSPWMRC
        ;;
    "sxhkdrc")
        edit $SXHKDRC
        ;;
    "update")
        exec_cmd "a-update"
        ;;
    "lfrc")
        edit $LFRC
        ;;
    "polybar")
        edit $POLYBAR
        ;;
    "xinitrc")
        edit $XINITRC
        ;;
    "xresources")
        edit $XRESOURCES
        ;;
    "kitty")
        edit $KITTY
        ;;
    *)
        not_valid_msg $choice
        exit
        ;;
esac
