#!/usr/bin/bash

. ~/colors.sh

BG=$BACKGROUND
FG=$FOREGROUND
SELECTED_BG=$c8
SELECTED_FG=$BLACK
PROMPT="🚀"
FONT="CaskaydiaCove Nerd Font-12"
dmenu_run -p "$PROMPT" -fn "$FONT" -nb $BG -nf $FG -sb $SELECTED_BG -sf $SELECTED_FG 


