#!/usr/bin/env bash 
ROOT_DIR=$HOME/.config/neofetch
THUMB_DIR=$ROOT_DIR/thumbnails
KEY=$(date +%S%N%w%H%y%M)

create_bac() {
    DIR="BAC-$KEY-thumbnails"
    echo "Creating backup to $DIR"
    mv $THUMB_DIR $ROOT_DIR/$DIR
}
move() {
        echo "Moving images... "
        mkdir $THUMB_DIR
       cp -r $1/*.{png,jpg} $THUMB_DIR/
        echo "Images Moved!!!"
}

create() {
    if [[ ! -d $THUMB_DIR ]]; then
        echo "Creating Directory $THUMB_DIR."
        move $1
    else
        create_bac
        move $1
    fi
}
create $1
