#!/bin/bash
if [ -n "$1" ]; then
    if [ -f "$1" ]; then
        echo "Opening file $1"
        typora $1&
        exit 1
    else 
        echo "$1 doesnot exist as a file"
        exit 1
    fi
else 
    echo "Parameter not passed"
fi
