#!/usr/bin/env bash

#. "$HOME/.config/theme-manager-bspwm/conf"
SDIR="$HOME/.config/rofi/launchers/text/"

windows=($(bspc query -N -n .window.hidden))                                                
index=$(for i in "${!windows[@]}"; do printf "%s %s |" $i "$(xtitle ${windows[i]})"; done) 

IFS='|' read -r -a array <<<$index;


#MENU=$(printf ${index%?} | dmenu -i -p '')
MENU=$(printf "%s\n" "${array[@]}"| dmenu -i -p 'Minimized windows')


[[ ! -z "$MENU" ]] && bspc node "${windows[${MENU%% *}]}" -g hidden=off                                       
