#!/bin/bash

. "$HOME/.cache/wal/colors.sh"

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc |
    column -t -s $'\t' |
    rofi -dmenu -i -markup-rows -no-show-icons \
    -p "🤟" \
    -width 1000 \
    -lines 15 \
    -yoffset 40 \
    -opacity "75" \
    -location 0 \
    -color-enabled true \
    -color-normal "$background, $foreground, $background, $cursor , $color0" \
    -color-window "$background" \
    -theme-str 'entry { placeholder: ""; }' \


