#!/usr/bin/env bash
copy_dir() {
    echo "[✗] Copying theme-manager-bspwm ==> $HOME/.config/"
    cp -r .config/theme-build/theme-manager-bspwm $HOME/.config/
    echo "[✗] Done...."

}

theme_manage() {
    if [[ -d $HOME/.config/theme-manager-bspwm ]]; 
    then 
        echo "[✗] theme-manager-bspwm directory exist. Want to override? [yes] / [no]"
        read yesno
      if [[ ${yesno,,} = "yes" ]];
      then 
          copy_dir
      elif [[ ${yesno,,} = "no" ]]; then
          echo "[✗] You can manually configured instead :)"
          exit 0
      else
          echo ":/ Bad choice..."
          exit 0
      fi
  else 
      echo "[✗] Fresh installation..."
      copy_dir
    fi
}

theme_manage
$HOME/.config/theme-manager-bspwm/configure
