#!/bin/bash

## Environment
source $HOME/.profile
xrdb ~/.Xresources

xsetroot -cursor_name left_ptr


PRIMARY_MONITOR=eDP-1
SECONDARY_MONITOR=HDMI-1
bspc monitor -d web code office fun torrent book discord 8
bspc config focus_follows_pointer true
bspc config border_width 5
bspc config window_gap 5
bspc config focused_border_color "$(getxres color11)" 
bspc config normal_border_color "$(getxres background)"
bspc config active_border_color "$(getxres color5)"
bspc config presel_feedback_color "$(getxres color2)"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8



bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config focus_follows_pointer   true

#Remove all rule first
bspc rule -r *:*

# browsers rule
bspc rule -a firefox private=on desktop=web state=tiled

# coding

# terminal
bspc rule -a kitty state=tiled

# video player
bspc rule -a smplayer state=tiled desktop=fun follow=on
bspc rule -a mpc state=tiled desktop=fun follow=on


# office
bspc rule -a *:*:LibreOffice state=floating desktop=office follow=on



#torrent
bspc rule -a qbittorrent state=tiled desktop=torrent follow=on
bspc rule -a qBittorrent state=tiled desktop=torrent follow=on

# IDE / code editor
bspc rule -a Code state=tiled desktop=code follow=off
bspc rule -a code state=tiled desktop=code follow=off


#  wallpaper
. $HOME/.fehbg

#initiate polybar
bash $HOME/.config/polybar/launch &

#start picom
picom -b

# document viewer
bspc rule -a Evince state=tiled desktop=book follow=on
bspc rule -a calibre state=tiled desktop=book follow=on
bspc rule -a calibre-gui state=tiled desktop=book follow=on

# discord
bspc rule -a discord state=tiled desktop=discord



#flameshot
flameshot &

#exec dunst daemon
DUNST_DIR=$HOME/.config/dunst
dunst -conf $DUNST_DIR/dunstrc


