#!/bin/bash

## Environment
source $HOME/.profile
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
getcolors

xsetroot -cursor_name left_ptr


bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &
autostart.sh
bspc config focus_follows_pointer true
bspc config border_width 4
bspc config window_gap 5
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 32
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8



bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config focus_follows_pointer   true

#Remove all rule first
bspc rule -r *:*

bspc rule -a kitty follow=off state=tiled center=true
bspc rule -a Alacritty follow=on state=floating center=true
bspc rule -a notion-app follow=on state=floating center=true
bspc rule -a discord state=floating follow=on center=true
bspc rule -a google-chrome-stable follow=off
bspc rule -a xdman-Main state=floating center=true

#reset padding before polybar
#bspc config top_padding 10
#bspc config bottom_padding 10

#exec dunst daemon
dunst \
-geom "300x5-30+20" -frame_width "1" -font "Source Code Variable 11" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$GREEN" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$FOREGROUND" -cfr "$RED" &

