#!/bin/bash

## Environment
source $HOME/.profile


##GET THEMES
. "$HOME/.config/theme-manager-bspwm/conf"
##GET COLORS
. "$HOME/.cache/wal/colors.sh"

red="#CD113B"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              5

bspc config focused_border_color "$color2"
bspc config active_border_color "$color8"
bspc config presel_feedback_color "$color0"



bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#reset padding before polybar
bspc config top_padding 10
bspc config bottom_padding 10

killall -9 sxhkd dunst

pgrep -x sxhkd > /dev/null || sxhkd &

#panel bar
bash $HOME/.config/polybar/$PTHEME/launch.sh
$HOME/.config/autostart

#dunst
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Iosevka Term 9" \
-lb "$background" -lf "$foreground" -lfr "$color3" \
-nb "$background" -nf "$foreground" -nfr "$color3" \
-cb "$background" -cf "$red" -cfr "$red" &
