#!/usr/bin/env bash

connected=""
disconnected=""
while true; do
    nc -z 8.8.8.8 53 >/dev/null 2>&1
    online=$?
    if [ $online -eq 0 ]; then
        echo "$connected" ; sleep 25
    else
        echo "$disconnected" ; sleep 0.5
    fi
done

